### ISSUE TITLE
unable to install adafruit-circuitpython-charlcd from requirements.txt

### ISSUE THREAD

**Issue by Vertikar** [olixr/MudPi#13]
using sudo pip3 install adafruit-circuitpython-charlcd works fine

**Comment by olixr** [comment]
The latest fix I pushed will resolve this via https://github.com/mudpi/mudpi-core/commit/a44caa1d73d47ea4858df8582dfbf69be41b7d94 

Pull in latest changes and run `pip3 install -r requirements.txt` to test.

**Comment by olixr** [comment]
I tested this on my own setup using Raspberry pi zero debian 10. 

Confirmed the new changes work and resolve this issue. 

Closing.
