### ISSUE TITLE
Option to run only one relay at time of queue relay operations and voltage sensor integration to run relays only if main power supply to run water pump is available

### ISSUE THREAD

**Issue by drmaddy736** [olixr/MudPi#27]
For systems run on  main power supply(irrigular) to run pumps from borewell or well there could be interruption due to power loss of pump(with raspberry pi running on battery all the time). In such situation system should check if main power supply is available to run the relays. Also in case interruption, at the end of whole schedule, system should check if all relays were run for scheduled time/duration and if not then start auto watering for remaining duration. E.g if schedule was to run relay1for 10min and due to interuption it ran for only 5 min then at the end of schedule of all relays, there should be automated watering for 5 min for ralay1.
Also option to queue in additional triggered relay activations could be awesome feature. Thank u.

**Comment by olixr** [comment]
I am going to put this into my internal notes and close this as I would like to keep the issues open just for bug reports. 

Also if you would like to share some of these ideas with me an the community we sometimes discuss batches of updates to take on. You can join us on discord https://discord.gg/daWg2YH
