### ISSUE TITLE
Configuring remote redis in mudpi.config broken

### ISSUE THREAD

**Issue by P33ry** [olixr/MudPi#4]
# Description
When trying to configure a remote redis to be used by _mudpi-core_ inside the _mudpi.config_, the settings are ignored and it tries to default to a local connection.

# Reproduction
1. Setup _mudpi-core_ on host1
2. Setup a redis server on host2
3. Configure _mudpi-core_ to use the redis server on host2
4. Start _mudpi-core_ and see it trying to connect to a local redis on host1

### Current Workaround
Editing the hard-coded connection details in __variables.py__ lets you define the connection details

**Comment by olixr** [comment]
I published a huge refactor and updates in v0.9.0. Changing the `redis` config should now work across the library. All the workers are set to use a singleton of the connection.

This should be now possible as of PR https://github.com/mudpi/mudpi-core/pull/11
